# Generated by Django 5.2.8 on 2025-11-15 20:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('mpesa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Category name (e.g., Tithe, Offering, Building Fund)', max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Short code used as M-Pesa account reference (e.g., TITHE, OFFER)', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this category')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this category is currently accepting contributions')),
            ],
            options={
                'verbose_name': 'Contribution Category',
                'verbose_name_plural': 'Contribution Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Contribution amount in KES', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('transaction_date', models.DateTimeField(db_index=True, help_text='When the contribution was made')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this contribution')),
                ('member', models.ForeignKey(help_text='Member who made this contribution', on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='members.member')),
                ('mpesa_transaction', models.OneToOneField(blank=True, help_text='Associated M-Pesa transaction', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contribution', to='mpesa.mpesatransaction')),
                ('category', models.ForeignKey(help_text='Category of this contribution', on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='contributions.contributioncategory')),
            ],
            options={
                'verbose_name': 'Contribution',
                'verbose_name_plural': 'Contributions',
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['-transaction_date', 'status'], name='contributio_transac_e2adcd_idx'), models.Index(fields=['member', '-transaction_date'], name='contributio_member__a1f6ae_idx'), models.Index(fields=['category', '-transaction_date'], name='contributio_categor_238c75_idx')],
            },
        ),
    ]
