# Generated by Django 5.2.8 on 2026-01-19 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
        ('members', '0004_userrole'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this admin assignment is active')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='User who assigned this admin role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_category_admins', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(help_text='Category this admin manages', on_delete=django.db.models.deletion.CASCADE, related_name='category_admins', to='contributions.contributioncategory')),
                ('member', models.ForeignKey(help_text='Member assigned as category admin', on_delete=django.db.models.deletion.CASCADE, related_name='category_admin_roles', to='members.member')),
            ],
            options={
                'verbose_name': 'Category Admin',
                'verbose_name_plural': 'Category Admins',
                'indexes': [models.Index(fields=['member', 'is_active'], name='contributio_member__f80aee_idx'), models.Index(fields=['category', 'is_active'], name='contributio_categor_0ac94d_idx'), models.Index(fields=['is_active', '-created_at'], name='contributio_is_acti_d8326a_idx')],
                'unique_together': {('member', 'category')},
            },
        ),
    ]
