# Generated by Django 5.2.8 on 2026-02-02 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_categoryadmin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='entered_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who entered this contribution manually', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_contributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contribution',
            name='entry_type',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('manual', 'Manual Entry'), ('cash', 'Cash'), ('envelope', 'Envelope')], db_index=True, default='mpesa', help_text='How this contribution was entered into the system', max_length=20),
        ),
        migrations.AddField(
            model_name='contribution',
            name='manual_receipt_number',
            field=models.CharField(blank=True, db_index=True, help_text='Receipt number for manual/cash/envelope entries', max_length=100, null=True),
        ),
    ]
