# Generated by Django 5.2.8 on 2026-02-02 18:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0003_contribution_entered_by_contribution_entry_type_and_more'),
        ('members', '0005_member_import_batch_id_member_is_guest'),
        ('mpesa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='contribution_group_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Groups multiple contributions made in a single transaction'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='mpesa_transaction',
            field=models.ForeignKey(blank=True, help_text='Associated M-Pesa transaction (multiple contributions can share one transaction)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='mpesa.mpesatransaction'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['contribution_group_id', '-transaction_date'], name='contributio_contrib_5119f8_idx'),
        ),
    ]
