# Generated by Django 5.2.8 on 2025-11-15 20:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant_request_id', models.CharField(max_length=100, unique=True)),
                ('checkout_request_id', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(db_index=True, max_length=12, validators=[django.core.validators.RegexValidator(message='Phone number must be in format 254XXXXXXXXX', regex='^254\\d{9}$')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_reference', models.CharField(max_length=100)),
                ('transaction_desc', models.CharField(max_length=255)),
                ('mpesa_receipt_number', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('result_desc', models.TextField(blank=True, null=True)),
                ('result_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'M-Pesa Transaction',
                'verbose_name_plural': 'M-Pesa Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'status'], name='mpesa_mpesa_created_f0ddd9_idx'), models.Index(fields=['phone_number', '-created_at'], name='mpesa_mpesa_phone_n_54461e_idx')],
            },
        ),
        migrations.CreateModel(
            name='MpesaCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant_request_id', models.CharField(db_index=True, max_length=100)),
                ('checkout_request_id', models.CharField(db_index=True, max_length=100)),
                ('result_code', models.CharField(max_length=10)),
                ('result_desc', models.TextField()),
                ('raw_data', models.JSONField()),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callbacks', to='mpesa.mpesatransaction')),
            ],
            options={
                'verbose_name': 'M-Pesa Callback',
                'verbose_name_plural': 'M-Pesa Callbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
