# Generated by Django 5.2.8 on 2026-02-25 18:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='C2BTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trans_id', models.CharField(db_index=True, help_text='M-Pesa transaction ID (e.g., RKTQDM7W6S)', max_length=100, unique=True)),
                ('trans_time', models.DateTimeField(help_text='Transaction timestamp from M-Pesa')),
                ('trans_amount', models.DecimalField(decimal_places=2, help_text='Amount paid by customer', max_digits=10)),
                ('business_short_code', models.CharField(help_text='Business short code (Pay Bill number)', max_length=20)),
                ('bill_ref_number', models.CharField(db_index=True, help_text='Account reference entered by customer (maps to category code)', max_length=100)),
                ('msisdn', models.CharField(db_index=True, help_text='Customer phone number in 254XXXXXXXXX format', max_length=12, validators=[django.core.validators.RegexValidator(message='Phone number must be in format 254XXXXXXXXX', regex='^254\\d{9}$')])),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('org_account_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Organization account balance after transaction', max_digits=12, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed')], db_index=True, default='received', max_length=20)),
                ('validation_result', models.CharField(blank=True, help_text='Result of validation: accepted or rejected', max_length=20)),
            ],
            options={
                'verbose_name': 'C2B Transaction',
                'verbose_name_plural': 'C2B Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'status'], name='mpesa_c2btr_created_7dde61_idx'), models.Index(fields=['msisdn', '-created_at'], name='mpesa_c2btr_msisdn_a9c75d_idx'), models.Index(fields=['bill_ref_number', '-created_at'], name='mpesa_c2btr_bill_re_067d7c_idx')],
            },
        ),
        migrations.CreateModel(
            name='C2BCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('callback_type', models.CharField(choices=[('validation', 'Validation'), ('confirmation', 'Confirmation')], db_index=True, help_text='Whether this was a validation or confirmation callback', max_length=20)),
                ('trans_id', models.CharField(db_index=True, help_text='M-Pesa transaction ID from callback', max_length=100)),
                ('raw_data', models.JSONField(help_text='Complete raw callback payload for audit')),
                ('processed', models.BooleanField(db_index=True, default=False, help_text='Whether this callback has been fully processed')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callbacks', to='mpesa.c2btransaction')),
            ],
            options={
                'verbose_name': 'C2B Callback',
                'verbose_name_plural': 'C2B Callbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
