# Generated by Django 5.2.8 on 2026-02-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0002_c2b_transaction_and_callback'),
    ]

    operations = [
        migrations.AddField(
            model_name='c2btransaction',
            name='match_method',
            field=models.CharField(blank=True, choices=[('exact', 'Exact'), ('fuzzy', 'Fuzzy'), ('manual', 'Manual')], help_text='How the category was matched: exact, fuzzy, or manual', max_length=10),
        ),
        migrations.AddField(
            model_name='c2btransaction',
            name='matched_category_code',
            field=models.CharField(blank=True, help_text='Category code that was actually matched (useful for fuzzy matches)', max_length=20),
        ),
        migrations.AlterField(
            model_name='c2btransaction',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('unmatched', 'Unmatched'), ('failed', 'Failed')], db_index=True, default='received', max_length=20),
        ),
    ]
