# Generated by Django 5.2.8 on 2026-01-13 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(help_text='Announcement title', max_length=200)),
                ('content', models.TextField(help_text='Announcement content/description')),
                ('publish_date', models.DateTimeField(db_index=True, help_text='When this announcement should be published')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this announcement is currently active')),
                ('priority', models.IntegerField(default=0, help_text='Higher priority announcements appear first (0 is lowest)')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-priority', '-publish_date'],
                'indexes': [models.Index(fields=['-priority', '-publish_date'], name='content_ann_priorit_c7588a_idx'), models.Index(fields=['is_active', '-publish_date'], name='content_ann_is_acti_a70955_idx')],
            },
        ),
        migrations.CreateModel(
            name='Devotional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(help_text='Devotional title', max_length=200)),
                ('content', models.TextField(help_text='Devotional content (supports markdown)')),
                ('author', models.CharField(help_text='Author name', max_length=100)),
                ('scripture_reference', models.CharField(blank=True, help_text='Bible scripture reference (e.g., John 3:16)', max_length=200)),
                ('publish_date', models.DateTimeField(db_index=True, help_text='Publication date')),
                ('is_published', models.BooleanField(db_index=True, default=False, help_text='Whether this devotional is published')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured devotionals appear prominently on the landing page')),
                ('featured_image_url', models.URLField(blank=True, help_text='Optional featured image URL', validators=[django.core.validators.URLValidator()])),
            ],
            options={
                'verbose_name': 'Devotional',
                'verbose_name_plural': 'Devotionals',
                'ordering': ['-publish_date'],
                'indexes': [models.Index(fields=['is_published', '-publish_date'], name='content_dev_is_publ_313631_idx'), models.Index(fields=['is_featured', '-publish_date'], name='content_dev_is_feat_ce5ce9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(help_text='Event title', max_length=200)),
                ('description', models.TextField(help_text='Event description')),
                ('event_date', models.DateField(db_index=True, help_text='Event date')),
                ('event_time', models.TimeField(help_text='Event time')),
                ('location', models.CharField(help_text='Event location/venue', max_length=300)),
                ('registration_link', models.URLField(blank=True, help_text='Optional registration/RSVP link', validators=[django.core.validators.URLValidator()])),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this event is currently active')),
                ('featured_image_url', models.URLField(blank=True, help_text='Optional featured image URL', validators=[django.core.validators.URLValidator()])),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['event_date', 'event_time'],
                'indexes': [models.Index(fields=['is_active', 'event_date'], name='content_eve_is_acti_354ffb_idx'), models.Index(fields=['event_date', 'event_time'], name='content_eve_event_d_58e466_idx')],
            },
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(help_text='Video title', max_length=200)),
                ('video_id', models.CharField(help_text='YouTube video ID (e.g., dQw4w9WgXcQ from youtube.com/watch?v=dQw4w9WgXcQ)', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Video description')),
                ('category', models.CharField(choices=[('sermon', 'Sermon'), ('worship', 'Worship'), ('testimony', 'Testimony'), ('teaching', 'Teaching'), ('event', 'Event'), ('other', 'Other')], default='other', help_text='Video category', max_length=20)),
                ('publish_date', models.DateTimeField(db_index=True, help_text='Publication date')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured videos appear prominently on the landing page')),
            ],
            options={
                'verbose_name': 'YouTube Video',
                'verbose_name_plural': 'YouTube Videos',
                'ordering': ['-publish_date'],
                'indexes': [models.Index(fields=['-publish_date'], name='content_you_publish_b775f1_idx'), models.Index(fields=['is_featured', '-publish_date'], name='content_you_is_feat_1180a9_idx'), models.Index(fields=['category', '-publish_date'], name='content_you_categor_316453_idx')],
            },
        ),
    ]
