# Generated by Django 5.2.8 on 2026-02-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='channel_id',
            field=models.CharField(blank=True, help_text='YouTube channel ID (populated for synced videos)', max_length=50),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Video duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Last time this video was synced from YouTube API', null=True),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='like_count',
            field=models.IntegerField(blank=True, help_text='YouTube like count (updated on sync)', null=True),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='playlist_id',
            field=models.CharField(blank=True, help_text='YouTube playlist ID (populated for playlist-synced videos)', max_length=50),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('channel', 'YouTube Channel'), ('playlist', 'YouTube Playlist')], db_index=True, default='manual', help_text='Source of the video (manual entry, channel sync, or playlist sync)', max_length=20),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='view_count',
            field=models.IntegerField(blank=True, help_text='YouTube view count (updated on sync)', null=True),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='youtube_published_at',
            field=models.DateTimeField(blank=True, help_text='Original YouTube publication date', null=True),
        ),
        migrations.AddIndex(
            model_name='youtubevideo',
            index=models.Index(fields=['source', '-publish_date'], name='content_you_source_4886c3_idx'),
        ),
    ]
