# Generated by Django 5.2.8 on 2025-11-15 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(db_index=True, help_text='Phone number in format 254XXXXXXXXX (for M-Pesa)', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in format 254XXXXXXXXX', regex='^254\\d{9}$')])),
                ('email', models.EmailField(blank=True, help_text='Optional email address', max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('member_number', models.CharField(db_index=True, help_text='Unique member identification number', max_length=50, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether the member is currently active')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='members_mem_last_na_92a910_idx'), models.Index(fields=['is_active', '-created_at'], name='members_mem_is_acti_003359_idx')],
            },
        ),
    ]
