# Generated by Django 5.2.8 on 2025-11-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, help_text='Phone number this OTP was sent to', max_length=12)),
                ('code', models.CharField(help_text='6-digit OTP code', max_length=6)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this OTP has been used')),
                ('expires_at', models.DateTimeField(help_text='When this OTP expires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verification_attempts', models.IntegerField(default=0, help_text='Number of failed verification attempts')),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', '-created_at'], name='members_otp_phone_n_1ff0df_idx'), models.Index(fields=['code', 'is_verified'], name='members_otp_code_3a1d47_idx')],
            },
        ),
    ]
