# Generated by Django 5.2.8 on 2025-11-22 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_otp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('treasurer', 'Treasurer'), ('pastor', 'Pastor'), ('member', 'Member')], help_text="User's role in the system", max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this role assignment is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'indexes': [models.Index(fields=['user', 'is_active'], name='members_use_user_id_c3c00e_idx'), models.Index(fields=['role', 'is_active'], name='members_use_role_55a3fc_idx')],
                'unique_together': {('user', 'role')},
            },
        ),
    ]
