# Generated by Django 5.2.8 on 2026-02-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='import_batch_id',
            field=models.CharField(blank=True, db_index=True, help_text='Batch ID if member was imported via CSV/Excel', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='is_guest',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this is a guest member (auto-created from contribution)'),
        ),
    ]
